### ISSUE TITLE
RSG namespace

### ISSUE THREAD

**Issue by Levrden** [markkorput/Computils#1]
Hei,
i have imported all the files into an empty projet, an d i have this error

> Assets\Computils-master\Scripts\Generic\Facade.cs(42,10): error CS0246: The type or namespace name 'RSG' could not be found (are you missing a using directive or an assembly reference?)

How can I fix it ?
thanks

**Comment by markkorput** [comment]
Hey @Levrden thanks for your interest in this package. So far I've been using it mostly myself for personal experiments so it hasn't been properly packaged yet for distribution. I just updated the [README](https://github.com/markkorput/Computils) with some instruction.

TL;DR
you also need [this C-Sharp-Promise](https://github.com/markkorput/C-Sharp-Promise) package and [this fusetools](https://gitlab.com/shortnotion/fusetools) package.

**Comment by Levrden** [comment]
Your screenshots are curious, i want to see howyou made them !
so thanks for the fast answer, i have cloned the repo using git, like you explain in the readme, and unity asked me to update api automatically, but now there is a problem with the fusetooll package

`Assets\fusetools\Scripts\DragHandler.cs(4,19): error CS0234: The type or namespace name 'UI' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)`

**Comment by markkorput** [comment]
Which version of the Unity Editor are you using?

**Comment by markkorput** [comment]
I just tried creating a blank 3D Unity project on Mac with Unity Editor 2019.2.0f1 and added the three packages and most things seem to work. You're probably gonna want to look at the GravityDemo by the way.

**Comment by Levrden** [comment]
I tried with the 2019.2.0b4, still the same, but it worked with the 2019.2.0f1, thanks !

**Comment by markkorput** [comment]
Alright, I hope that works for you to try it out. It's a very incomplete little experiment, so I'm probably not gonna bother properly packing it up any time soon :)
